import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Registration from "./Components/Registration";
import Header from "./Components/Header";

export default function Home() {
  const hello = api.user.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4">
      <button
                        className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-black focus:outline-none max-w-24"
                    ><Link href="/regristrationPage">Register</Link>
                    </button>
                    <button
                        className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-black focus:outline-none max-w-24"
                    ><Link href="/login">Login</Link>
                    </button>
      </main>
    </>
  );
}
